1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно.

In [1]:
import numpy as np
a = np.linspace(12,23,12)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [2]:
a_1 = a.reshape(2,6)
a_1

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [3]:
a_2= a.reshape(6,2)
a_2

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [4]:
a_3= a.reshape(3,4)
a_3

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [5]:
a_4= a.reshape(4,3)
a_4

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [6]:
a_5= a.reshape(12, 1)
a_5

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк). 

In [7]:
a_1 = a.reshape(-1,6)
a_1

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [8]:
a_2 = a.reshape(-1,3)
a_2

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [9]:
a_3 = a.reshape(6,-1)
a_3

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [10]:
a_4 = a.reshape(3,-1)
a_4

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [11]:
a_5 = a.reshape(12,-1)
a_5

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [12]:
# Одномерный массив это массив с элементами.
# Двумерный массив это массив с элементами, внутри массива.
example = a.reshape(12, 1)
example
# Ответ: массив Numpy состоящий и одного столбца и 12 строк нельзя назвать одномерным.

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [21]:
arr_2d = np.random.randn(3,4)
arr_2d

array([[ 1.29645733, -0.52328883, -0.4629725 , -0.2122279 ],
       [ 1.09990425,  0.54172378,  0.13357555, -0.83079691],
       [ 0.38467745,  0.79432602, -1.22612404, -0.55433706]])

In [23]:
arr_1d = arr_2d.flatten()
arr_1d

array([ 1.29645733, -0.52328883, -0.4629725 , -0.2122279 ,  1.09990425,
        0.54172378,  0.13357555, -0.83079691,  0.38467745,  0.79432602,
       -1.22612404, -0.55433706])

In [25]:
arr_1d.size

12

In [26]:
arr_2d.size

12