In [1]:
import numpy as np

In [2]:
a = [i for i in range(10)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
b = np.array(a)

In [5]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.array([i for i in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
c = (1,2,3,4,5)

In [8]:
np.array(c)

array([1, 2, 3, 4, 5])

In [9]:
type(np.array(c))

numpy.ndarray

In [10]:
d = np.array(a, dtype = float)

In [11]:
a = [0,1,2,3,4.1]

In [12]:
d = np.array(a, dtype = float)

In [13]:
d

array([0. , 1. , 2. , 3. , 4.1])

In [14]:
c = np.array(a, dtype = str)

In [15]:
c

array(['0', '1', '2', '3', '4.1'], dtype='<U3')

In [16]:
c[2]

'2'

In [17]:
c[0]

'0'

In [18]:
b.ndim

1

In [19]:
b.shape

(10,)

In [20]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [21]:
x.shape

(3, 3)

In [22]:
x.size

9

In [23]:
x[2][2]

9

In [24]:
x[2, 2]

9

In [25]:
x[0:2, 0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
x[:2, :3]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
x[0:1, 0:]

array([[1, 2, 3]])

In [28]:
c = x[0:, 1:]

In [29]:
c

array([[2, 3],
       [5, 6],
       [8, 9]])

In [30]:
c[1, 1] = 999

In [31]:
x

array([[  1,   2,   3],
       [  4,   5, 999],
       [  7,   8,   9]])

In [32]:
c

array([[  2,   3],
       [  5, 999],
       [  8,   9]])

In [33]:
c = x[0:,1:].copy()

In [34]:
c[1,1] = 777

In [35]:
c

array([[  2,   3],
       [  5, 777],
       [  8,   9]])

In [36]:
x

array([[  1,   2,   3],
       [  4,   5, 999],
       [  7,   8,   9]])

#### Data types

In [44]:
y32 = np.array([1.,2.,3.], dtype = np.float32)

In [45]:
y32

array([1., 2., 3.], dtype=float32)

In [46]:
y64 = np.array([1.,2.,3.], dtype = np.float64)

In [47]:
y64

array([1., 2., 3.])

In [54]:
z32 = np.array([1,2,3], dtype = np.int32)

In [55]:
z32

array([1, 2, 3])

In [56]:
z64 = np.array([1,2,3.], dtype = np.int64)

In [57]:
z64

array([1, 2, 3], dtype=int64)