In [1]:
import numpy as np

In [2]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
a = np.ones((5,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [13]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

In [14]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [16]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [17]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

In [19]:
np.random.sample()

0.5243664966593535

In [20]:
np.random.sample(3)

array([0.63283269, 0.93324363, 0.40964907])

In [21]:
np.random.sample((2,3))

array([[0.7487049 , 0.68897825, 0.89495958],
       [0.83604251, 0.71457395, 0.98700428]])

In [22]:
np.random.sample((48,64,3))

array([[[0.94673024, 0.09221825, 0.89837639],
        [0.3433259 , 0.90764941, 0.85752984],
        [0.77621875, 0.03376696, 0.70812949],
        ...,
        [0.07438895, 0.57430215, 0.65441994],
        [0.54214188, 0.6245102 , 0.64965655],
        [0.32623283, 0.54147392, 0.05033096]],

       [[0.5050465 , 0.97719121, 0.90220307],
        [0.02989366, 0.73068987, 0.1553365 ],
        [0.42604652, 0.70846196, 0.52239848],
        ...,
        [0.06130608, 0.67964448, 0.9409712 ],
        [0.14548145, 0.7965392 , 0.51097559],
        [0.74032392, 0.09373332, 0.2500535 ]],

       [[0.0560965 , 0.09098377, 0.20410626],
        [0.17999033, 0.11645801, 0.00221617],
        [0.47480373, 0.1332979 , 0.44812633],
        ...,
        [0.54803643, 0.98182365, 0.92118052],
        [0.69211046, 0.48587074, 0.22471462],
        [0.40776247, 0.20291415, 0.76496658]],

       ...,

       [[0.21717777, 0.76437694, 0.62180271],
        [0.90144298, 0.57328302, 0.44711549],
        [0.41637572, 0

In [25]:
np.random.randn(10)

array([ 0.52965824, -1.51468318, -2.56830001, -1.12985617, -0.91005141,
       -0.18220712,  0.66788844,  0.70825323, -0.20608803,  0.67605844])

In [26]:
np.random.randn(3,4)

array([[ 0.27725814,  0.38939235,  0.29251429, -0.84013772],
       [-0.89493526,  0.39564572,  0.73408563, -1.02507357],
       [-1.29566025,  0.21880942, -1.35605422,  0.53348357]])

In [27]:
np.random.randint(0, 100, 10)

array([36, 21, 67,  7, 83, 53, 66, 99, 17, 97])

In [28]:
np.random.randint(0, 10, (3,4))

array([[3, 9, 1, 2],
       [2, 7, 3, 9],
       [4, 5, 3, 6]])

In [29]:
b = np.array([1,5,2,7,3,8,6,4])

In [31]:
np.random.choice(b)

4

In [32]:
np.random.choice(b, 3)

array([8, 5, 4])

In [45]:
np.random.seed(42)

In [46]:
np.random.randint(0, 10, 3)

array([6, 3, 7])

In [47]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a.resize(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
a = np.zeros((2,3))

In [60]:
b = np.ones((2,3))

In [62]:
v = np.vstack((a,b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [67]:
np.concatenate((a,b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
h = np.hstack((a,b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [70]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [71]:
np.concatenate((a,b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [73]:
d = np.dstack([a,b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])