In [1]:
import numpy as np

#### Data selection

In [3]:
a = np.random.randint(0,20,10)
a

array([ 1, 19, 15, 18, 16,  6, 10,  8, 12,  4])

In [4]:
a[a > 10]

array([19, 15, 18, 16, 12])

In [5]:
a[(a > 10) & (a % 2 == 0)]

array([18, 16, 12])

In [6]:
a[(a > 10) | (a % 2 == 0)]

array([19, 15, 18, 16,  6, 10,  8, 12,  4])

In [7]:
a

array([ 1, 19, 15, 18, 16,  6, 10,  8, 12,  4])

In [8]:
np.where(a > 10)

(array([1, 2, 3, 4, 8], dtype=int64),)

In [9]:
a[np.where(a > 10)]

array([19, 15, 18, 16, 12])

In [10]:
a = [1, 4, 7]
b = [9, 2, 5]

In [11]:
np.where([True, False, True], a, b)

array([1, 2, 7])

In [12]:
a = np.array([[1,3,9,9],[5,0,1,5],[2,7,3,5]])

In [13]:
a[[0,2,1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [14]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]], dtype=int64)

In [15]:
a[:, 0].argsort()

array([0, 2, 1], dtype=int64)

In [16]:
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [17]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.random.shuffle(a)

In [19]:
a

array([4, 2, 6, 8, 5, 9, 3, 0, 7, 1])

In [20]:
a = np.arange(12).reshape(4,3)

In [21]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
np.random.shuffle(a)

In [23]:
a

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [24]:
a = np.arange(1,7).reshape(2,3)

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6]])

#### Logarithm

In [28]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [29]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [30]:
a.sum()

21

In [31]:
a.sum(axis = 0)

array([5, 7, 9])

In [32]:
a.sum(axis = 1)

array([ 6, 15])

In [33]:
10 + a 

array([[11, 12, 13],
       [14, 15, 16]])

In [34]:
a = np.arange(12).reshape(3,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

b = np.arange(12,24).reshape(-1,4)
b

In [36]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#### Brodcasting

In [39]:
a = np.array([[2,5],[3,4],[6,1]])
a

array([[2, 5],
       [3, 4],
       [6, 1]])

In [40]:
b = np.array([1,2])
b

array([1, 2])

In [41]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

In [43]:
c = np.array([[1],[2],[3]])
c

array([[1],
       [2],
       [3]])

In [45]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

#### Statistcs

In [47]:
a = np.random.randint(0,12,(3,4))
a

array([[ 8, 10,  6, 10],
       [ 3, 11,  6,  4],
       [ 2,  8,  1,  8]])

In [48]:
a.min()

1

In [49]:
a.min(axis = 0)

array([2, 8, 1, 4])

In [50]:
a.min(axis = 1)

array([6, 3, 1])

In [51]:
a.mean(axis = 0)

array([4.33333333, 9.66666667, 4.33333333, 7.33333333])

In [52]:
a.mean(axis = 1)

array([8.5 , 6.  , 4.75])

In [53]:
a.std(axis = 0)

array([2.62466929, 1.24721913, 2.3570226 , 2.49443826])

In [54]:
np.save('a.npy', a)

In [55]:
b = np.load('a.npy')

In [56]:
b

array([[ 8, 10,  6, 10],
       [ 3, 11,  6,  4],
       [ 2,  8,  1,  8]])